on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: run the action
      id: hello 
      uses: ./
      with:
        myInput: 'abdulaziz al'
      
    - name: output
      run: |
        echo ${{ steps.hello.outputs.memory }}
        echo "total memory output"
      
